/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cuda_mult.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(14a69c5a65b31e74b19e74afd107b9b9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <blnxngsched/cuda_mult.h>
// pydoc.h is automatically generated in the build directory
#include <cuda_mult_pydoc.h>

void bind_cuda_mult(py::module& m)
{

    using cuda_mult    = gr::blnxngsched::cuda_mult;


    py::class_<cuda_mult, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<cuda_mult>>(m, "cuda_mult", D(cuda_mult))

        .def(py::init(&cuda_mult::make),
           D(cuda_mult,make)
        )
        



        ;




}








