/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cuda_fanout.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(58f418d6f72d52c1673f2b5904263fbd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <blnxngsched/cuda_fanout.h>
// pydoc.h is automatically generated in the build directory
#include <cuda_fanout_pydoc.h>

void bind_cuda_fanout(py::module& m)
{

    using cuda_fanout    = gr::blnxngsched::cuda_fanout;


    py::class_<cuda_fanout, gr::block, gr::basic_block,
        std::shared_ptr<cuda_fanout>>(m, "cuda_fanout", D(cuda_fanout))

        .def(py::init(&cuda_fanout::make),
           D(cuda_fanout,make)
        )
        



        ;




}








