/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fake_hw_loopback.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a27f95992c11a52d99b7462ff4a7bb03)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <blnxngsched/fake_hw_loopback.h>
// pydoc.h is automatically generated in the build directory
#include <fake_hw_loopback_pydoc.h>

void bind_fake_hw_loopback(py::module& m)
{

    using fake_hw_loopback    = gr::blnxngsched::fake_hw_loopback;


    py::class_<fake_hw_loopback, gr::block, gr::basic_block,
        std::shared_ptr<fake_hw_loopback>>(m, "fake_hw_loopback", D(fake_hw_loopback))

        .def(py::init(&fake_hw_loopback::make),
           py::arg("batch_size"),
           D(fake_hw_loopback,make)
        )
        



        ;




}








